

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  # Expose Vite dev server
    networks:
      - prod-network
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    env_file:
      - .env  # Load environment variables from the .env file
    ports:
      - "3001:3001"
    networks:
      - prod-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default_authentication_plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql/db.sql:/docker-entrypoint-initdb.d/db.sql  # SQL import directory
      - $HOME/database:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - prod-network
   
networks:
  prod-network:
    driver: bridge
     