services:
  frontend:
    # when we use github action we remove this
    # build:
    #   context: ./frontend
    # mage from docker registry
    image: marwane2003/aurax:frontend-latest
    ports:
      - "80:80" # Expose Vite dev server
    networks:
      - prod-network
    depends_on:
      - backend
  backend:
    # when we use github action we remove this
    # build:
    #   context: ./backend
    # image from docker registry
    image: marwane2003/aurax:backend-latest
    env_file:
      - .env # Load environment variables from the .env file
    ports:
      - "3001:3001"
    networks:
      - prod-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default_authentication_plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql/db.sql:/docker-entrypoint-initdb.d/db.sql # SQL import directory
      - $HOME/database:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - prod-network
  # watcher every time the image updated the container laso updated
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
    - WATCHTOWER_CLEANUP=true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 frontend backend
    restart: unless-stopped  # Ensure Watchtower restarts automatically if needed
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge
