name: pipeline
on:
  push:
    branches:
      - 'master'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      # check the code in my repo , tells workflw to use actions/checkout version 4
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: itbeeazy/frontend:latest

      - name: build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: itbeeazy/backend:latest
          
      # - name: run docker-compose 
      #   run: |
      
      #     docker-compose -f docker-compose.prod.yml up --build -d